system_state = {
    "is_session_active": False,
    "timer_minutes": 0,
    "blocked_sites": [],
    "is_face_detected": True,
    "face_height": 100,
    "is_phone_detected": False,
    "is_blocked_site_detected": False,
    "current_url": "",
    "is_alarm_active": False,
    "is_warning_started": False,
    "warning_start_time": None,
    "session_start_time": None,
    "alarm_count": 0,
}
